[tool.poetry]
name = "django-blog"
version = "0.1.0"
description = ""
authors = ["88ArtemSmirnov88 <artembanchik@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
